[versions]
kotlinMultiplatformPlugin = "9.1.1"
composeGradlePlugin = "1.10.3"
gradle = "9.3.1"
kotter = "1.2.1"
kotlin = "2.3.20"
junit = "4.13.2"
lifecycleViewmodelCompose = "2.10.0"
lifecycleRuntimeCompose = "2.10.0"
coil = "3.5.0"
material3 = "1.9.0"
materialIconsExtended = "1.7.3"
slf4j = "2.0.17"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.11.0"
javafx = "21.0.2"
kotlinxCoroutines = "1.10.2"
ktor = "3.4.2"
clikt = "5.1.0"
mordant = "3.0.2"
dotenv = "6.5.1"
koin = "4.2.1"
mockk = "1.14.9"
tamboui = "0.2.0"
scrimage = "4.4.2"
graalvm = "1.0.0"
sqldelight = "2.3.2"
sqlite-jdbc = "3.53.0.0"
jmtc = "0.0.3"
jaudiotagger = "2.0.18"
kdiscordipc = "5041c5b036"
brotli = "0.1.2"
newpipe = "v0.26.1"
media3 = "1.10.0"
vlcj = "4.12.1"
agp = "9.1.1"
compose-plugin = "1.10.3"
androidx-activityCompose = "1.13.0"

[libraries]
kotlinMultiplatformPlugin = { module = "com.android.kotlin.multiplatform.library:com.android.kotlin.multiplatform.library.gradle.plugin", version.ref = "kotlinMultiplatformPlugin" }
composeCompilerPlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
composePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeGradlePlugin" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotter = { module = "com.varabyte.kotter:kotter-jvm", version.ref = "kotter" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinSerializationPlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorClientLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktorClientOkhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorClientMock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktorClientEncoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
mordant = { module = "com.github.ajalt.mordant:mordant", version.ref = "mordant" }
mordantCoroutines = { module = "com.github.ajalt.mordant:mordant-coroutines", version.ref = "mordant" }
mordantMarkdown = { module = "com.github.ajalt.mordant:mordant-markdown", version.ref = "mordant" }
dotenv = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }
koinCore = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koinAndroid = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koinCompose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koinComposeViewModel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeGradlePlugin" }
tambouiTui = { module = "dev.tamboui:tamboui-tui", version.ref = "tamboui" }
tambouiToolkit = { module = "dev.tamboui:tamboui-toolkit", version.ref = "tamboui" }
tamboouiJline = { module = "dev.tamboui:tamboui-jline3-backend", version.ref = "tamboui" }
tambouiImage = { module = "dev.tamboui:tamboui-image", version.ref = "tamboui" }
scrimageCore = { module = "com.sksamuel.scrimage:scrimage-core", version.ref = "scrimage" }
slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4jSimple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
sqldelightRuntime = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
sqldelightCoroutinesExtensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelightSqliteDriver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelightGradlePlugin = { module = "app.cash.sqldelight:gradle-plugin", version.ref = "sqldelight" }
sqliteJdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
jmtc = { module = "io.github.selemba1000:JavaMediaTransportControls", version.ref = "jmtc" }
jaudiotagger = { module = "com.github.RouHim:jaudiotagger", version.ref = "jaudiotagger" }
kdiscordipc = { module = "com.github.Adriianh:KDiscordIPC", version.ref = "kdiscordipc" }
brotli = { module = "org.brotli:dec", version.ref = "brotli" }
newpipeExtractor = { module = "com.github.TeamNewPipe:NewPipeExtractor", version.ref = "newpipe" }
junit = { module = "junit:junit", version.ref = "junit" }
ktorClientDarwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktorClientAndroid = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
sqldelightAndroidDriver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelightNativeDriver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
coilCompose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coilNetworkKtor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
vlcj = { module = "uk.co.caprica:vlcj", version.ref = "vlcj" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeGradlePlugin" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeGradlePlugin" }

[bundles]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
ktor = ["ktorClientCore", "ktorClientCio", "ktorClientContentNegotiation", "ktorSerializationKotlinxJson", "ktorClientLogging"]
tamboui = ["tambouiTui", "tambouiToolkit", "tamboouiJline", "tambouiImage"]

[plugins]
graalvmNative = { id = "org.graalvm.buildtools.native", version.ref = "graalvm" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidKotlinMultiplatform = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
